version: '3.9'

services:
  redis:
    image: redis:6.2
    container_name: redisartemis
    volumes:
      - redis:/data
    ports:
      - 6379:6379
  artemislistener:
    image: artemislistener
    container_name: artemislistener
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    volumes:
      - artemislistener:/tmp
volumes:
  artemislistener:
  redis:
